version: '3'

tasks:
  base:
    cmds:
      - docker build --target base . -t cw-alert-router:base
  test:
    deps: [base]
    cmds:
      - docker run -t cw-alert-router:base go test -v ./...
  build:
    cmds:
      - docker build --target build -t cw-alert-router:build .
  publish:
    deps: [build]
    cmds:
      - docker run -v "$(PWD):/target" --rm cw-alert-router:build cp /app/function.zip /target
  cov:
    cmds:
      - go test -v -cverprofile=coverage.out -covermode=atomic -coverpkg=./... ./...
  clean:
    cmds:
      - docker rmi -f cw-alert-router:build

