name: Build & Test
on:
    push:
        branches: [ main ]
    pull_request:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: checkout
            uses: actions/checkout@v3
          - name: Install task
            run: sudo sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
          - name: Run tests
            run: task test
          - name: Build
            run: task build
    fossa-scan:
        runs-on: ubuntu-latest
        steps:
          - name: "Checkout Code"
            uses: actions/checkout@v3

          - name: "Run FOSSA Scan"
            uses: fossas/fossa-action@main
            with:
              api-key: ${{secrets.FOSSAAPIKEY}}

          - name: "FOSSA Tests"
            uses: fossas/fossa-action@main
            with:
              api-key: ${{secrets.FOSSAAPIKEY}}
              run-tests: true
