name: Build & Test
on:
    push:
        branches: [ main ]
    pull_request:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: checkout
            uses: actions/checkout@v3
          - name: Install task
            run: sudo sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
          - name: Run tests
            run: task test
          - name: Build
            run: task build
    fossa-scan:
        runs-on: ubuntu-latest
        steps:
          - name: "Checkout Code"
            uses: actions/checkout@v3

          - name: "Run FOSSA Scan"
            uses: fossas/fossa-action@main
            with:
              api-key: ${{secrets.FOSSAAPIKEY}}

          - name: "FOSSA Tests"
            id: fossa-tests
            uses: fossas/fossa-action@main
            with:
              api-key: ${{secrets.FOSSAAPIKEY}}
              run-tests: true

          - name: "Comment"
            uses: actions/github-script@v7
            with:
              script: |
                github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: steps.fossa-tests.outputs.result
                })
